### ISSUE TITLE
리로딩

### ISSUE THREAD

**Issue by roy0424** [soulee-dev/ft_transcendence_fe#37]
채팅방 관리페이지에서 노티 소켓 받고 리로딩 안해줌

채팅방 페이지에서 킥 밴 어드민부여 하는데 리로딩 안해줌

**Comment by soulee-dev** [comment]
- [ ] 채팅방 관리페이지에서 노티 소켓 받고 리로딩 안해줌
- [ ] 채팅방 페이지에서 킥 밴 어드민부여 하는데 리로딩 안해줌
- [ ] 관리자 페이지 새로운 사람 들어오면 리로딩
